---
- include_tasks: "install-{{ ansible_os_family | lower }}.yml"
  tags:
    - 'chronograf'
  when:
    - not chronograf_containerized
- include_tasks: "service.yml"
  when:
    - not chronograf_containerized